import frappeUIPreset from 'frappe-ui/tailwind'
import colors from 'tailwindcss/colors'

export default {
  presets: [frappeUIPreset],
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
    './node_modules/frappe-ui/src/**/*.{vue,js,ts,jsx,tsx}',
    '../node_modules/frappe-ui/src/**/*.{vue,js,ts,jsx,tsx}',
    './node_modules/frappe-ui/frappe/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      // Khôi phục toàn bộ bảng màu Tailwind chuẩn
      colors: {
        slate:   colors.slate,
        gray:    colors.gray,
        zinc:    colors.zinc,
        neutral: colors.neutral,
        stone:   colors.stone,
        red: {
          50: 'var(--thaco-red-soft)',
          100: 'var(--thaco-red-soft)',
          200: 'var(--thaco-red-soft)',
          300: 'var(--thaco-red-soft)',
          400: 'var(--thaco-red)',
          500: 'var(--thaco-red)',
          600: 'var(--thaco-red)',
          700: 'var(--thaco-red)',
          800: 'var(--thaco-red)',
          900: 'var(--thaco-red)',
          DEFAULT: 'var(--thaco-red)',
        },
        orange:  colors.orange,
        yellow:  colors.yellow,
        lime:    colors.lime,
        green:   colors.green,
        emerald: colors.emerald,
        teal:    colors.teal,
        cyan:    colors.cyan,
        sky:     colors.sky,
        blue:    colors.blue,
        indigo:  colors.indigo,
        violet:  colors.violet,
        purple:  colors.purple,
        fuchsia: colors.fuchsia,
        pink:    colors.pink,
        // Các biến màu từ thiết kế Snuol
        canvas: 'var(--canvas)',
        paper: 'var(--paper)',
        surface: 'var(--surface)',
        hover: 'var(--hover)',
        ink: {
          DEFAULT: 'var(--ink)',
          2: 'var(--ink-2)',
        },
        muted: 'var(--muted)',
        faint: 'var(--faint)',
        border: 'var(--border)',
        divider: 'var(--divider)',
        line: 'var(--line)',
        brand: {
          50: 'var(--brand-tint)',
          100: 'var(--brand-soft)',
          500: 'var(--brand)',
          600: 'var(--brand-deep)',
          700: 'var(--brand-700)',
          DEFAULT: 'var(--brand)',
          deep: 'var(--brand-deep)',
          soft: 'var(--brand-soft)',
          tint: 'var(--brand-tint)',
        },
        // Semantic tokens (§6.1) — dùng cho StatusBadge và state
        success: { 50: 'var(--sage-soft)', 600: 'var(--sage)', DEFAULT: 'var(--sage)' },
        warning: { 50: 'var(--amber-soft)', 700: 'var(--amber)', DEFAULT: 'var(--amber)' },
        danger: { 50: 'var(--rose-soft)', 600: 'var(--rose)', DEFAULT: 'var(--rose)' },
        info: { 50: 'var(--info-soft)', 600: 'var(--info)', DEFAULT: 'var(--info)' },
        'thaco-red': {
          DEFAULT: 'var(--thaco-red)',
          soft: 'var(--thaco-red-soft)',
        },
        sage: {
          DEFAULT: 'var(--sage)',
          soft: 'var(--sage-soft)',
        },
        clay: {
          DEFAULT: 'var(--clay)',
          soft: 'var(--clay-soft)',
        },
        amber: {
          DEFAULT: 'var(--amber)',
          soft: 'var(--amber-soft)',
        },
        rose: {
          50: 'var(--rose-soft)',
          100: 'var(--rose-soft)',
          200: 'var(--rose-soft)',
          300: 'var(--rose-soft)',
          400: 'var(--rose)',
          500: 'var(--rose)',
          600: 'var(--rose)',
          700: 'var(--rose)',
          800: 'var(--rose)',
          900: 'var(--rose)',
          DEFAULT: 'var(--rose)',
          soft: 'var(--rose-soft)',
        },
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        display: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        serif: ['Inter', 'Georgia', 'serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
    },
  },
  plugins: [],
}
